### ISSUE TITLE
特定の条件で線形の表示が乱れる

### ISSUE THREAD

**Issue by Riku-Horn** [konawasabi/tsutsuji-trackcomputer#1]
## 概要
Mapファイル内の距離程に「+$distance」を入力して Tsutsuji trackcomputer をリロードすると、数秒間「応答なし」を挟んで、その距離程の処理が乱れた線形が表示される

## 再現手順
Mapファイル内の距離程に「+$distance」を入力する
（この画像は、すべての距離程にこの操作を行った状態で撮影）
![tsutsuji_issue_B](https://github.com/konawasabi/tsutsuji-trackcomputer/assets/112320600/c11d269a-7226-4e7d-977d-5ec5c71c4565)

## 正常な表示
この画像のような表示（距離程には他の文字列を入力した状態で撮影）
![tsutsuji_issue_A](https://github.com/konawasabi/tsutsuji-trackcomputer/assets/112320600/d8e8a5c9-8eca-4bad-9de1-48e42e4e4bf9)

## 動作環境

Tsutsuji trackcomputer Version 1.7.1
Python 3.11.3

OS : Windows 10 Home, 22H2, 19045.3269
CPU : Intel Core i7 9750H
RAM : 16GB x 1 2400MHz
GPU : NVIDIA Geforce GTX 1650 mobile

**Comment by konawasabi** [comment]
distance変数には直前に指定した距離程の値が代入されます。
たとえば、
```
10000+distance;
Curve.BeginTransition();
10050+distance;
Curve.Begin(300,0.01);
10250+distance;
Curve.BeginTransition();
10300+distance;
Curve.End();
```
というマップファイルを入力した場合、distance変数の初期値は0となっているので、
```
10000; //10000+distance;
Curve.BeginTransition();
20050; //10050+distance;
Curve.Begin(300,0.01);
30300; //10250+distance;
Curve.BeginTransition();
40600; //10300+distance;
Curve.End();
```
と解釈されます。

このため、元マップでの距離程が増えるに従って、

1. 緩和曲線長さ、円曲線長さが想定よりも大幅に増加した線形を計算してしまっている

2. Tsutsujiでは自軌道1つあたりの総延長に応じて内部で保持する軌道座標データが増加するので、軌道座標の計算・プロットに時間がかかっている

ということが考えられます。

全ての距離程に+distanceする、という操作で想定している線形が構成できるか検討いただけますでしょうか。
また、当方で状況を再現するため、差し支えない範囲で読み込ませたマップファイルの内容をお教えいただければ幸いです。

**Comment by konawasabi** [comment]
補足です。
変数名$distance は、tsutsuji内部では直前の距離程を示す規定変数distance ($なし)と同一のものとして扱われます。

**Comment by Riku-Horn** [comment]
ご返信ありがとうございます。
将来的な逆延伸を想定して「$distance」という変数をすべての距離程に設定しましたが、これがtsutsuji内部では違うものとして扱われてしまったということですね。

[Tsutsuji_distance.zip](https://github.com/konawasabi/tsutsuji-trackcomputer/files/12100656/Tsutsuji_distance.zip)

**Comment by konawasabi** [comment]
マップデータの提供ありがとうございます。当方でも同様の現象を確認しました。
暫定的な対策として、お手数ですが変数名を$distance以外の適当なものに変えていただければと思います。

BVE本体では、distance, $distance変数は別個のものとして扱われていることを確認したので、折を見てtsutsuji/kobushi側もそのように修正したいと思います。

**Comment by konawasabi** [comment]
distance, $distance変数を独立して扱うような修正を行いました。
Kobushi-trackviewerを最新バージョンに更新していただけますでしょうか。
https://github.com/konawasabi/kobushi-trackviewer

マップファイルを読み込み、軌道座標を計算する処理はkobushi側に集約しているため、このような処置となっております。
Tsutsuji trackcomputerは今回修正ありません。

**Comment by Riku-Horn** [comment]
アップデートして表示を確認したところ、正常な線形が表示されました。

ありがとうございました
